name: Run tests and publish the report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.0.0 pytest-html==4.1.1 faker==22.6.0 requests==2.31.0
      
      - name: Run tests and generate report
        run: |
          pytest --html=./testing_results/
      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: testing_results
