name: Run tests and publish the report

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest==8.0.0 allure-pytest==2.13.2 faker==22.6.0 requests==2.31.0
      
      - name: Install Allure command-line
        run: |
          wget -O allure-2.15.0.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.15.0/allure-commandline-2.15.0.tgz
          tar -zxvf allure-2.15.0.tgz
          echo "export PATH=\$PATH:$(pwd)/allure-2.15.0/bin" >> $GITHUB_ENV

      - name: Run tests and generate Allure reports
        run: |
          pytest --alluredir=./allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        run: |
          mkdir -p gh-pages/allure-results
          cp -r allure-results/* gh-pages/allure-results
          allure serve -o gh-pages/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: gh-pages
